"""
This type stub file was generated by pyright.
"""

from owlready2.namespace import *
from owlready2.prop import *

class AnnotatedRelation:
  def __init__(self, s, p, o) -> None:
    ...
  
  def __repr__(self): # -> str:
    ...
  
  def get_properties(self): # -> set[Any]:
    ...
  
  def __getattr__(self, attr): # -> AnnotatedRelationValueList:
    ...
  
  def __setattr__(self, attr, value): # -> None:
    ...
  


class AnnotatedRelationValueList(CallbackListWithLanguage):
  __slots__ = ...
  def __init__(self, l, obj, Prop) -> None:
    ...
  
  def __hash__(self) -> int:
    ...
  


class AnnotationPropertyClass(PropertyClass):
  _owl_type = ...
  inverse = ...
  def __getitem__(Annot, entity): # -> AnnotatedRelationValueList | list[Any] | IndividualValueList:
    ...
  
  def __setitem__(Annot, index, values): # -> None:
    ...
  
  def __call__(Prop, type, c, *args):
    ...
  
  _get_indirect_values_for_class = ...


class AnnotationProperty(Property, metaclass=AnnotationPropertyClass):
  namespace = ...
  @classmethod
  def is_functional_for(Prop, o): # -> Literal[False]:
    ...
  


class comment(AnnotationProperty):
  namespace = ...


class label(AnnotationProperty):
  namespace = ...


class backwardCompatibleWith(AnnotationProperty):
  namespace = ...


class deprecated(AnnotationProperty):
  namespace = ...


class incompatibleWith(AnnotationProperty):
  namespace = ...


class isDefinedBy(AnnotationProperty):
  namespace = ...


class priorVersion(AnnotationProperty):
  namespace = ...


class seeAlso(AnnotationProperty):
  namespace = ...


class versionInfo(AnnotationProperty):
  namespace = ...


