"""
This type stub file was generated by pyright.
"""

from owlready2.namespace import *
from owlready2.entity import *
from owlready2.prop import *
from owlready2.individual import *
from owlready2.class_construct import *

def close_world(self, Properties=..., close_instance_list=..., recursive=...):
  ...

