"""
This type stub file was generated by pyright.
"""

from owlready2.namespace import *
from owlready2.entity import *
from owlready2.prop import *
from owlready2.class_construct import *

class AllDisjoint:
  def __init__(self, entities, ontology=..., bnode=...) -> None:
    ...
  
  def __getattr__(self, attr): # -> CallbackList | Any:
    ...
  
  def destroy(self): # -> None:
    ...
  
  def __repr__(self): # -> str:
    ...
  


AllDifferent = AllDisjoint
def partition(mother, children): # -> None:
  ...

