"""
This type stub file was generated by pyright.
"""

from typing import Optional, Union
from owlready2.disjoint import AllDisjoint
from owlready2.class_construct import Construct
from owlready2.entity import EntityClass, ThingClass
from owlready2.prop import PropertyClass
from owlready2.namespace import Ontology

_DL_SYNTAX = ...
_FACETS = ...
def dl_render_terminology_str(onto: Ontology, show_disjoint: bool = ..., show_domain: bool = ..., show_range: bool = ..., show_inverse: bool = ..., show_characteristics: bool = ...) -> str:
    ...

def dl_render_class_str(klass: ThingClass, show_disjoint: bool = ...) -> str:
    ...

def dl_render_prop_str(prop: PropertyClass, show_domain: bool = ..., show_range: bool = ..., show_inverse: bool = ..., show_characteristics: bool = ...) -> str:
    ...

def dl_render_disjoint_str(disjoint: AllDisjoint, klass: Optional[ThingClass] = ...) -> str:
    ...

def dl_render_concept_str(concept: Union[Construct, EntityClass]) -> str:
    ...

