"""
This type stub file was generated by pyright.
"""

from owlready2 import *

IGNORE_DOMAINLESS_PROPERTY = ...
descr = ...
def configure_editobj_from_ontology(onto): # -> None:
  ...

PROP_CHILDREN_GROUPS = ...
def get_prop_children_group(Prop): # -> PropChildrenGroup:
  ...

class PropChildrenGroup:
  def __init__(self, Prop) -> None:
    ...
  
  def define_children_groups(self): # -> None:
    ...
  


class RangeRestriction:
  def __init__(self, Prop, domain, ranges) -> None:
    ...
  
  def __repr__(self): # -> str:
    ...
  
  def get_classes(self): # -> set[Any]:
    ...
  


class RangeClassOnly(RangeRestriction):
  ...


class RangeClassExclusion(RangeRestriction):
  ...


class RangeInstanceOnly(RangeRestriction):
  ...


class RangeInstanceExclusion(RangeRestriction):
  ...


VALUES_LISTERS = ...
class ValuesLister:
  def __init__(self, Prop, domain, range_restrictions) -> None:
    ...
  
  def values_have_children(self): # -> bool | None:
    ...
  
  def available_values(self, subject): # -> list[Any]:
    ...
  
  def range_match_classes(self, classes): # -> Literal[True] | None:
    ...
  


