"""
This type stub file was generated by pyright.
"""

import editobj3.editor as editor
from owlready2 import *
from editobj3.observe import *

__all__ = ["EditedInstances", "OntologyInstanceEditor"]
class EditedInstances:
  def __init__(self, ontology, Class) -> None:
    ...
  
  def get_instances(self):
    ...
  
  instances = ...
  def remove_instance(self, instance): # -> None:
    ...
  
  def __str__(self) -> str:
    ...
  
  def details(self): # -> str:
    ...
  
  def addable_values(self): # -> list[Any]:
    ...
  


descr = ...
class TabPaneRepartitor(editor.PaneRepartitor):
  def __init__(self, instance_editor, tab_edited_class) -> None:
    ...
  
  def is_displayed_in_other_tab(self, attribute, o_Class): # -> Literal[False]:
    ...
  
  def is_displayed_in_hierarchy_pane(self, attribute, o, field_class=...): # -> bool:
    ...
  
  def is_displayed_in_attribute_pane(self, attribute, o, field_class=...): # -> Literal[False]:
    ...
  


class OntologyInstanceEditor(editor.EditorTabbedDialog):
  _Qt_MODULE = ...
  _HTML_MODULE = ...
  def __init__(self, gui=..., master=..., direction=..., on_validate=..., edit_child_in_self=..., undo_stack=..., on_close=..., menubar=...) -> None:
    ...
  
  def on_dialog_closed(self, *args): # -> bool:
    ...
  
  def set_ontology(self, ontology, edited_classes=...): # -> None:
    ...
  
  def add_tab_for_class(self, Class):
    ...
  
  def on_save(self, *args): # -> None:
    ...
  
  def on_save_as(self, *args): # -> None:
    ...
  


