"""
This type stub file was generated by pyright.
"""

import editobj3.editor_qt as editor_qt
from owlready2 import *
from owlready2.instance_editor import *

class QtOntologyInstanceEditor(OntologyInstanceEditor, editor_qt.QtEditorTabbedDialog):
  def check_save(self): # -> Literal[0, 1] | None:
    ...
  
  def prompt_save_filename(self):
    ...
  


