"""
This type stub file was generated by pyright.
"""

"""ntriples_diff.py

Compute the differences between 2 NTriples files. Take care of symmetric relations
and different blank node naming.

Usage:

  ntriple_diff.py onto.nt : canonize the NTriples file.

  ntriple_diff.py onto1.nt onto2.nt : compare the two NTriples files.

Options:

  --short : shortify IRI and literal (more Human readable).
  --ignore_plain_literal : treat plain literal as string (this is a workaround for a bug in OWLAPI).
"""
ignore_plain_literal = ...
def shortify(triples): # -> list[Any]:
  ...

symmetric_predicates = ...
useless_triples = ...
class Blank:
  def __init__(self) -> None:
    ...
  
  def add_triple(self, s, p, o): # -> None:
    ...
  
  def get_name(self): # -> str:
    ...
  


def canonize(nt): # -> list[Any]:
  ...

def diff(nt1, nt2): # -> tuple[list[Any], list[Any]]:
  ...

if __name__ == "__main__":
  ...
