"""
This type stub file was generated by pyright.
"""

import rdflib
import rdflib.store
from owlready2.base import *

class TripleLiteRDFlibStore(rdflib.store.Store):
  context_aware = ...
  def __init__(self, world) -> None:
    ...
  
  def add(self, xxx_todo_changeme, context, quoted=...): # -> None:
    ...
  
  def remove(self, xxx_todo_changeme, context=...): # -> None:
    ...
  
  def triples(self, triple_pattern, context=...): # -> Generator[tuple[tuple[Any, Any, Any], Any | None], Any, None]:
    ...
  
  def __len__(self, context=...): # -> int:
    ...
  
  def contexts(self, triple=...): # -> Generator[Any, Any, dict_values[Any, Any] | None]:
    ...
  
  def bind(self, prefix, namespace, override=...): # -> None:
    ...
  
  def namespace(self, prefix): # -> None:
    ...
  
  def prefix(self, namespace): # -> None:
    ...
  
  def namespaces(self): # -> Generator[tuple[Any, Any], Any, None]:
    ...
  
  def get_context(self, identifier_or_ontology):
    ...
  


class TripleLiteRDFlibGraph(rdflib.Graph):
  onto = ...
  def query_owlready(self, query, *args, **kargs): # -> Generator[Any | list[Any | int | locstr | str], Any, None]:
    ...
  
  def get_context(self, onto):
    ...
  
  def BNode(self):
    ...
  


