"""
This type stub file was generated by pyright.
"""

from owlready2.base import *
from owlready2.namespace import *
from owlready2.individual import *
from owlready2.prop import *

swrl = ...
class Variable(Thing):
  namespace = ...
  def __str__(self) -> str:
    ...
  
  def __repr__(self): # -> Any:
    ...
  
  def __init__(self, name=..., namespace=..., **kargs) -> None:
    ...
  


class body(ObjectProperty):
  namespace = ...


class head(ObjectProperty):
  namespace = ...


class classPredicate(ObjectProperty, FunctionalProperty):
  namespace = ...


class propertyPredicate(ObjectProperty, FunctionalProperty):
  namespace = ...


class arguments(ObjectProperty):
  namespace = ...


class builtin(ObjectProperty, FunctionalProperty):
  namespace = ...


_DATARANGES = ...
_NAME_2_DATARANGE = ...
class Imp(Thing):
  namespace = ...
  def __str__(self) -> str:
    ...
  
  def __repr__(self): # -> str:
    ...
  
  def __init__(self, name=..., namespace=..., **kargs) -> None:
    ...
  
  def __getattr__(self, attr): # -> OrderedValueList | list[Any] | Any | owlready2.individual._EquivalentToList | owlready2.entity._EquivalentToList:
    ...
  
  def get_variable(self, name, create=...): # -> Variable | None:
    ...
  
  def set_as_rule(self, rule, namespaces=...): # -> Self:
    ...
  
  def __destroy__(self, objs, datas): # -> None:
    ...
  


class _FixedArguments:
  def __init__(self, name=..., namespace=..., **kargs) -> None:
    ...
  
  def __str__(self) -> str:
    ...
  
  def __getattr__(self, attr): # -> ArgumentValueList:
    ...
  
  def __destroy__(self): # -> None:
    ...
  


class ClassAtom(_FixedArguments, Thing):
  namespace = ...
  def __repr__(self): # -> str:
    ...
  


class DataRangeAtom(_FixedArguments, Thing):
  namespace = ...
  def __repr__(self): # -> str:
    ...
  
  def __getattr__(self, attr): # -> ArgumentValueList:
    ...
  
  def __setattr__(self, attr, value): # -> None:
    ...
  


class SameIndividualAtom(_FixedArguments, Thing):
  namespace = ...
  def __repr__(self): # -> str:
    ...
  


class DifferentIndividualsAtom(_FixedArguments, Thing):
  namespace = ...
  def __repr__(self): # -> str:
    ...
  


class DatavaluedPropertyAtom(_FixedArguments, Thing):
  namespace = ...
  def __init__(self, name=..., namespace=..., **kargs) -> None:
    ...
  
  def __repr__(self): # -> str:
    ...
  


class IndividualPropertyAtom(_FixedArguments, Thing):
  namespace = ...
  def __init__(self, name=..., namespace=..., **kargs) -> None:
    ...
  
  def __repr__(self): # -> str:
    ...
  


_BUILTINS = ...
class BuiltinAtom(Thing):
  namespace = ...
  def __init__(self, name=..., namespace=..., **kargs) -> None:
    ...
  
  def __str__(self) -> str:
    ...
  
  def __repr__(self): # -> str:
    ...
  
  def __getattr__(self, attr): # -> OrderedValueList | list[Any] | Any | owlready2.individual._EquivalentToList | owlready2.entity._EquivalentToList:
    ...
  
  def __setattr__(self, attr, value): # -> None:
    ...
  
  def __destroy__(self): # -> None:
    ...
  


class OrderedValueList(CallbackList):
  __slots__ = ...
  def __init__(self, bn, obj, Prop) -> None:
    ...
  


class ArgumentValueList(CallbackList):
  __slots__ = ...
  def __init__(self, obj) -> None:
    ...
  


_RULE_PARSER = ...
