"""
This type stub file was generated by pyright.
"""

current_dir = ...
parent_dir = ...
def install_develop_mode(dist): # -> None:
    """
    `python setup.py develop` assumes a directory structure where the package
    to be installed lives in a subdirectory. This function assumes that this command
    has already been run. Now it remains to
        - adapt the path inside the <package_name>.egg-link-text file (-> parent_dir)
        - adapt the path inside easy_install.pth (-> parent_dir)
        - move the directory <package_name>.egg-info to parent_dir

    For safety reasons the following directory structure is assumed:

    <arbitrary_dir_name>/              <- the .egg-link will point here
    │
    ├── <package_name>/                <- all the source lives here
    │   ├── .git/
    │   ├── setup.py
    │   ├── setup_develop_mode.py
    │   └── ...
    └── <package_name.egg-info>/       <- autogenerated by setuptools, moved here by this function

    Note: No other directories or files are allowed inside <arbitrary_dir_name>.

    :param dist: setuptools.dist object
    :return:
    """
    ...

