"""
This type stub file was generated by pyright.
"""

from owlready2 import *
from owlready2.sparql.parser import *
from owlready2.sparql.func import FuncSupport

_RE_AUTOMATIC_INDEX = ...
_DEPRIORIZE_SUBQUERIES_OPT = ...
class Translator:
  def __init__(self, world, error_on_undefined_entities=...) -> None:
    ...
  
  def make_translator(self): # -> Translator:
    ...
  
  def parse(self, sparql): # -> PreparedSelectQuery | PreparedModifyQuery | None:
    ...
  
  def finalize(self): # -> PreparedSelectQuery | PreparedModifyQuery | None:
    ...
  
  def parse_inserts_deletes(self, triples, columns, is_insert): # -> list[Any]:
    ...
  
  def new_sql_query(self, name, parent, block, selects=..., distinct=..., solution_modifier=..., preliminary=..., extra_binds=..., copy_vars=..., is_delete=...): # -> SQLQuery | SQLCompoundQuery | SQLNestedQuery:
    ...
  
  def expand_prefix(self, prefix): # -> str:
    ...
  
  def abbreviate(self, entity):
    ...
  
  def new_var(self): # -> str:
    ...
  
  def new_parameter(self): # -> int:
    ...
  
  def get_recursive_preliminary_select(self, parent_query, triple, fixeds, fixed_vars, can_use_in, prelim_triples): # -> SQLRecursivePreliminaryQuery:
    ...
  


class PreparedQuery:
  def __init__(self, world, sql, column_names, column_types, nb_parameter, parameter_datatypes) -> None:
    ...
  
  def execute_raw(self, params=..., spawn=...): # -> None:
    ...
  
  def execute_raw_with_db(self, params, db):
    ...
  


class PreparedSelectQuery(PreparedQuery):
  def __getstate__(self): # -> list[Any]:
    ...
  
  def __setstate__(self, l): # -> None:
    ...
  
  def execute(self, params=..., execute_raw_result=..., spawn=...): # -> Generator[list[Any], Any, None]:
    ...
  
  def execute_flat(self, params=..., spawn=...): # -> Generator[Any | locstr | None, Any, None]:
    ...
  
  def execute_csv(self, params=..., separator=..., spawn=...): # -> str:
    ...
  
  def execute_tsv(self, params=..., spawn=...): # -> str:
    ...
  
  def execute_json(self, params=..., spawn=...): # -> str:
    ...
  
  def execute_xml(self, params=..., spawn=...): # -> LiteralString:
    ...
  


class PreparedModifyQuery(PreparedQuery):
  def __init__(self, world, sql, column_names, column_types, nb_parameter, parameter_datatypes, ontology, deletes, inserts, select_param_indexes) -> None:
    ...
  
  def __getstate__(self): # -> list[Any]:
    ...
  
  def __setstate__(self, l): # -> None:
    ...
  
  def execute_raw(self, params=..., spawn=...): # -> list[tuple[()]] | None:
    ...
  
  def execute_raw_with_db(self, params, db): # -> list[tuple[()]]:
    ...
  
  def execute(self, params=..., execute_raw_result=..., spawn=...):
    ...
  


class Column:
  def __init__(self, var, type, binding, name, index) -> None:
    ...
  
  def __repr__(self): # -> LiteralString:
    ...
  


class Variable:
  def __init__(self, name) -> None:
    ...
  
  def __repr__(self): # -> str:
    ...
  
  def get_binding(self, query):
    ...
  
  def update_type(self, type): # -> None:
    ...
  


class Table:
  def __init__(self, query, name, type=..., index=..., join=..., join_conditions=...) -> None:
    ...
  
  def __repr__(self): # -> str:
    ...
  
  def sql(self): # -> str:
    ...
  


class SQLQuery(FuncSupport):
  def __init__(self, name, parent=..., is_delete=...) -> None:
    ...
  
  def __repr__(self): # -> str:
    ...
  
  def sql(self): # -> str | LiteralString:
    ...
  
  def parse_distinct(self, distinct): # -> None:
    ...
  
  def parse_var(self, x): # -> Variable:
    ...
  
  def parse_selects(self, selects): # -> None:
    ...
  
  def expand_referenced_vars(self, var, r): # -> None:
    ...
  
  def prepare_bind(self, bind): # -> None:
    ...
  
  def parse_bind(self, bind): # -> None:
    ...
  
  def parse_filter(self, filter): # -> None:
    ...
  
  def add_subquery(self, sub): # -> None:
    ...
  
  def parse_triples(self, triples):
    ...
  
  def get_fix_levels(self, vars0, exclude_triple=...): # -> defaultdict[Any, float]:
    ...
  
  def can_use_in(self, orig_triple): # -> bool:
    ...
  
  def extract_triples(self, triples, vars, except_triple=...): # -> list[Triple | Filter | Bind]:
    ...
  
  def create_conditions(self, conditions, table, n, x, likelihood=...): # -> None:
    ...
  
  def try_create_in_conditions(self, conditions, x, prelim): # -> bool:
    ...
  
  def is_fixed(self, x): # -> bool:
    ...
  
  def finalize_columns(self): # -> None:
    ...
  


class SQLCompoundQuery:
  recursive = ...
  def __init__(self, name, parent, is_delete=...) -> None:
    ...
  
  def __repr__(self): # -> str:
    ...
  
  def append(self, query, operator=...): # -> None:
    ...
  
  def sql(self): # -> LiteralString | Literal['']:
    ...
  
  def finalize_compounds(self): # -> None:
    ...
  


class SQLNestedQuery(SQLQuery):
  def __init__(self, name, parent, is_delete=...) -> None:
    ...
  
  def finalize_columns(self): # -> None:
    ...
  
  def nested_sql(self): # -> str | LiteralString:
    ...
  
  def __str__(self) -> str:
    ...
  


class SQLRecursivePreliminaryQuery(SQLQuery):
  def __init__(self, name, triple, fixeds, fixed_vars, can_use_in, is_delete=..., parent_query=...) -> None:
    ...
  
  def set_column_names(self, names): # -> None:
    ...
  
  def build(self, triple, prelim_triples): # -> None:
    ...
  


class SQLStaticValuesPreliminaryQuery:
  recursive = ...
  def __init__(self, translator, name, static_values, is_delete=...) -> None:
    ...
  
  def sql(self): # -> str:
    ...
  


